### ISSUE TITLE
undefined method `configure' for HttpLog:Module

### ISSUE THREAD

**Issue by drnic** [trusche/httplog#38]
In development.rb & production.rb of rails app I have:

```ruby
Rails.application.configure do
  HttpLog.configure do |config|
    config.logger = Rails.logger
  end
```

But running `rails s` in dev or prod it explodes with:

```
/Users/drnic/Projects/dingo-projects/dingo-standalone-hub/config/environments/development.rb:9:in `block in <top (required)>': undefined method `configure' for HttpLog:Module (NoMethodError)
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/railtie.rb:209:in `instance_eval'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/railtie.rb:209:in `configure'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/config/environments/development.rb:1:in `<top (required)>'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/engine.rb:599:in `each'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/engine.rb:599:in `block in <class:Engine>'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `run'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/initializable.rb:44:in `each'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/drnic/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/config/environment.rb:5:in `<top (required)>'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/config.ru:3:in `require_relative'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/config.ru:3:in `block in <main>'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/config.ru:in `new'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/config.ru:in `<main>'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/server.rb:59:in `app'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/server.rb:77:in `start'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/bin/rails:9:in `require'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/bin/rails:9:in `<top (required)>'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /Users/drnic/.rvm/gems/ruby-2.3.3/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/bin/spring:15:in `require'
	from /Users/drnic/Projects/dingo-projects/dingo-standalone-hub/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

Ideas?

**Comment by trusche** [comment]
Sorry, that configuration is brand new for the not-yet-released version 0.99.0. Either use httplog from the master branch here, or use the configuration instructions of the last released version 0.3.3 from here: https://github.com/trusche/httplog/tree/v0.3.3

**Comment by trusche** [comment]
I hope to release 0.99.0 today btw.

**Comment by drnic** [comment]
Ahh ok. Thanks.

**Comment by trusche** [comment]
I've added a version warning to the README. 

BTW, I don't recommend using this in production, since it messes with the network stack. I haven't encountered any negative side effects yet, but that doesn't guarantee there aren't any.

**Comment by drnic** [comment]
Thanks; I spotted https://github.com/trusche/httplog/issues/18 thread.

The side effects of watching networking can't be much worse that the negative effects of an invisible networking stack doing the wrong thing :)
