### ISSUE TITLE
`log_status': uninitialized constant

### ISSUE THREAD

**Issue by Jasmine-Lognnes** [trusche/httplog#40]
When running the below script I get

```
D, [2017-04-12T15:43:07.738060 #29603] DEBUG -- : [httplog] Sending: GET https://example.com/bwtem
D, [2017-04-12T15:43:07.738148 #29603] DEBUG -- : [httplog] Data: 
D, [2017-04-12T15:43:07.738366 #29603] DEBUG -- : [httplog] Connecting: example.com:443
/usr/local/share/gems/gems/httplog-0.99.2/lib/httplog/http_log.rb:55:in `log_status': uninitialized constant #<Class:HttpLog>::Rack (NameError)
	from /usr/local/share/gems/gems/httplog-0.99.2/lib/httplog/adapters/httpclient.rb:28:in `do_get_block'
	from /usr/local/share/gems/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /usr/local/share/gems/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /usr/local/share/gems/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /usr/local/share/gems/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
	from /usr/local/share/gems/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
	from /usr/local/share/gems/gems/httpclient-2.8.3/lib/httpclient.rb:743:in `get'
	from ./test.rb:25:in `<main>'
```

```
#!/usr/bin/ruby

require 'httpclient'
require 'pp'
require 'kconv'    #seemed to be needed due to a bug..
require 'rubyntlm' # probably not needed directly?
require 'openssl'
require 'tempfile'
require 'nokogiri'
require 'mechanize'
require 'awesome_print'
require 'httplog' # require this *after* your HTTP gem of choice

user = 'test'
pass = 'test'
uri = URI 'https://example.com/bwtem'
domain = 'win.example.com'

cookie_file = Tempfile.new('cookie_jar.txt')
client = HTTPClient.new(default_header: {"User-Agent" => 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'})
client.set_cookie_store(cookie_file)
client.set_auth(nil, user, pass)
client.ssl_config.verify_mode = nil

r = client.get(uri, :follow_redirect => true)
```

**Comment by trusche** [comment]
You just need to require rack. This works:

```
#!/usr/bin/ruby

require 'httpclient'
require 'openssl'
require 'tempfile'
require 'nokogiri'
require 'rack'
require 'httplog' # require this *after* your HTTP gem of choice

user = 'test'
pass = 'test'
uri = URI 'https://example.com/bwtem'
domain = 'win.example.com'

cookie_file = Tempfile.new('cookie_jar.txt')
client = HTTPClient.new(default_header: {"User-Agent" => 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'})
client.set_cookie_store(cookie_file)
client.set_auth(nil, user, pass)
client.ssl_config.verify_mode = nil

r = client.get(uri, :follow_redirect => true)
```

However, rack is in fact a runtime dependency, so I've updated and release v0.99.3. If you install httplog with bundler, rack will now be present even when used outside of e.g. Rails.
