### ISSUE TITLE
Error: undefined method `log' for nil:NilClass

### ISSUE THREAD

**Issue by kevinelliott** [trusche/httplog#41]
When adding httplog `0.99.3` to a Rails 5 application and then setting logger to the one for Rails (as specified in the README), this error is presented:

```
  undefined method `log' for nil:NilClass
```

Configuration in `config/environments/development.rb` is as follows:

```
  HttpLog.configure do |config|
    config.logger = Rails.logger
  end
```

Backtrace:

```
httplog (0.99.3) lib/httplog/http_log.rb:33:in `log'
httplog (0.99.3) lib/httplog/http_log.rb:38:in `log_connection'
httplog (0.99.3) lib/httplog/adapters/net_http.rb:36:in `connect'
/Users/kevin/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/Users/kevin/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
/Users/kevin/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
httplog (0.99.3) lib/httplog/adapters/net_http.rb:21:in `block in request'
/Users/kevin/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
httplog (0.99.3) lib/httplog/adapters/net_http.rb:20:in `request'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/net.rb:33:in `block in request_with_newrelic_trace'
newrelic_rpm (4.1.0.333) lib/new_relic/agent.rb:438:in `disable_all_tracing'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/net.rb:32:in `request_with_newrelic_trace'
skylight (1.3.0) lib/skylight/probes/net_http.rb:26:in `request'
faraday (0.11.0) lib/faraday/adapter/net_http.rb:80:in `perform_request'
faraday (0.11.0) lib/faraday/adapter/net_http.rb:38:in `block in call'
faraday (0.11.0) lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
faraday (0.11.0) lib/faraday/adapter/net_http.rb:33:in `call'
faraday (0.11.0) lib/faraday/request/url_encoded.rb:15:in `call'
faraday (0.11.0) lib/faraday/rack_builder.rb:139:in `build_response'
faraday (0.11.0) lib/faraday/connection.rb:377:in `run_request'
oauth2 (1.3.1) lib/oauth2/client.rb:99:in `request'
oauth2 (1.3.1) lib/oauth2/client.rb:146:in `get_token'
oauth2 (1.3.1) lib/oauth2/strategy/auth_code.rb:30:in `get_token'
omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:89:in `build_access_token'
omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:73:in `callback_phase'
```

**Comment by kevinelliott** [comment]
For some reason I had to put the configuration into the `config.after_initialization` block, after which it resolved the error. This issue can be closed.

**Comment by trusche** [comment]
Hmm. I'll take a look, thanks for reporting this.

**Comment by trusche** [comment]
@kevinelliott If you move the original config block from `development.rb` to an initializer, does it work then? I suspect it will - in which case I'll update the documentation accordingly. 

Also, which Rails version - 5.1?
