### ISSUE TITLE
HttpLog undefined for plain ruby program

### ISSUE THREAD

**Issue by shouya** [trusche/httplog#45]
Hi devs,

Do I have to use this gem with Rails/Rack programs? Or anything special have to be done if I want to use the gem with a standalone ruby program.

Here's a small program that demonstrates the issue:

```ruby
# demo.rb
require 'http'
require 'httplog'

HTTP.get('http://example.org')
```

Running this program with `ruby demo.rb` yields:

```
D, [2017-07-19T14:53:48.658561 #74766] DEBUG -- : [httplog] Sending: GET http://example.org/
D, [2017-07-19T14:53:48.658660 #74766] DEBUG -- : [httplog] Data:
D, [2017-07-19T14:53:48.658702 #74766] DEBUG -- : [httplog] Connecting: example.org:80
/Users/shou/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httplog-0.99.6/lib/httplog/http_log.rb:56:in `log_status': uninitialized constant #<Class:HttpLog>::Rack (NameError)
	from /Users/shou/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httplog-0.99.6/lib/httplog/adapters/http.rb:27:in `block in <class:Client>'
	from /Users/shou/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/client.rb:41:in `request'
	from /Users/shou/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/chainable.rb:75:in `request'
	from /Users/shou/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/http-2.2.2/lib/http/chainable.rb:19:in `get'
	from demo.rb:4:in `<main>'
```

I just want to inspect the traffic over a very simple ruby program, but HttpLog then yields this exception. What can I do to circumvent it? Thank you very much!

**Comment by trusche** [comment]
It doesn't depend on Rails, but it uses Rack to parse HTTP status codes. I suppose that could be ditched, but it's really pretty simple to just include Rack. This works:

```
# demo.rb
require 'http'
require 'rack'
require 'httplog'

HTTP.get('http://example.org')
```

**Comment by shouya** [comment]
Would it be better if this gem add dependency for rack instead of leaving this to users?
