### ISSUE TITLE
undefined method `log' for ActiveSupport::BufferedLogger

### ISSUE THREAD

**Issue by rickcockerham** [trusche/httplog#48]
I have tried this in my development.rb
  HttpLog.configure do |hconfig|
      hconfig.logger = Rails.logger
    end

I did a google search and found this:

```
  Procyon::Application.configure do
...
   config.after_initialize do
    HttpLog.configure do |hconfig|
      hconfig.logger = Rails.logger
    end
  end
end
```

ruby 2.2.6
rails 3.2.22.5
httplog 0.99.7

Neither one works.  This is the error I get:

```
/.rvm/gems/ruby-2.2.6/gems/railties-3.2.22.5/lib/rails/commands/runner.rb:54:in `eval': undefined method `log' for #<ActiveSupport::BufferedLogger:0x000000042f0428> (NoMethodError)
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/httplog-0.99.7/lib/httplog/http_log.rb:35:in `log'
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/httplog-0.99.7/lib/httplog/http_log.rb:40:in `log_connection'
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/httplog-0.99.7/lib/httplog/adapters/net_http.rb:36:in `connect'
        from /home/pixie/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from /home/pixie/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from /home/pixie/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/httplog-0.99.7/lib/httplog/adapters/net_http.rb:21:in `block in request'
        from /home/pixie/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/httplog-0.99.7/lib/httplog/adapters/net_http.rb:20:in `request'
        from /home/pixie/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/net/http.rb:1398:in `send_entity'
        from /home/pixie/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/net/http.rb:1186:in `post'
        from /home/var/www/procyon/v5/lib/optimalblue.rb:21:in `oauth'
        from (eval):1:in `<top (required)>'
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/railties-3.2.22.5/lib/rails/commands/runner.rb:54:in `eval'
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/railties-3.2.22.5/lib/rails/commands/runner.rb:54:in `<top (required)>'
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/railties-3.2.22.5/lib/rails/commands.rb:64:in `require'
        from /home/pixie/.rvm/gems/ruby-2.2.6/gems/railties-3.2.22.5/lib/rails/commands.rb:64:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'

```

**Comment by trusche** [comment]
Hi @rickcockerham, I'm afraid this is most likely due to a backward incompatibility with Rails 3. The current stable release version of Rails is 5.1, the oldest version still receiving security updates is 4.2.  I'll happily accept a pull request to fix this for Rails 3, but I won't have the time to try and troubleshoot this myself. Closing for now.
